# Generated by Django 3.1.1 on 2020-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=5)),
                ('machine_type', models.CharField(choices=[('small', 'small'), ('large', 'large'), ('espresso', 'espresso')], max_length=10)),
                ('machine_model', models.CharField(choices=[('base', 'base'), ('premium', 'premium'), ('deluxe', 'deluxe')], max_length=10)),
                ('water_compatible', models.BooleanField()),
            ],
        ),
    ]
