# Generated by Django 3.1.1 on 2020-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
