# Generated by Django 3.1.1 on 2020-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200910_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.CharField(blank=True, choices=[('base', 'base'), ('premium', 'premium'), ('deluxe', 'deluxe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('small', 'small'), ('large', 'large'), ('espresso', 'espresso')], max_length=10),
        ),
    ]
